name: euroleague_analytics
version: "1.0.0"
config-version: 2

profile: euroleague_analytics

model-paths: ["models"]
test-paths: ["tests"]

models:
  euroleague_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
